"""Adicionar cliente_id em Transacao

Revision ID: f05bd0ee87e6
Revises: 9db2271c853b
Create Date: 2026-09-09 22:22:56.659325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05bd0ee87e6'
down_revision: Union[str, Sequence[str], None] = '9db2271c853b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'produtos', 'clientes', ['cliente_id'], ['id'])
    op.add_column('transacoes', sa.Column('cliente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transacoes', 'clientes', ['cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacoes', type_='foreignkey')
    op.drop_column('transacoes', 'cliente_id')
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'cliente_id')
    # ### end Alembic commands ###
